@ClientService.API_HostAddress = http://localhost:5011

GET {{ClientService.API_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{ClientService.API_HostAddress}}/api/clients
Accept: application/json

###
GET {{ClientService.API_HostAddress}}/api/clients/f0c3db71-e75c-48b7-b7a4-83ed994d43c0
Accept: application/json

###
POST {{ClientService.API_HostAddress}}/api/clients
Content-Type: application/json

{
  "fullName": "Alice Johnson",
  "email": "alice.johnson@example.com",
  "phoneNumber": "+1234567890"
}


###
PUT {{ClientService.API_HostAddress}}/api/clients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "id": "123e4567-e89b-12d3-a456-426614174000",
  "fullName": "Alice Johnson Updated",
  "email": "alice.johnson@example.com",
  "phoneNumber": "+1234567899"
}

###
DELETE {{ClientService.API_HostAddress}}/api/clients/123e4567-e89b-12d3-a456-426614174000