@InspectionService.API_HostAddress = http://localhost:5244

GET {{InspectionService.API_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{InspectionService.API_HostAddress}}/api/inspection/
Accept: application/json


### Get inspection by ID
GET {{InspectionService.API_HostAddress}}/api/inspection/b84481bd-25ee-491d-922b-08ddd69a9bbe
Accept: application/json

###
POST {{InspectionService.API_HostAddress}}/api/inspection/
Content-Type: application/json

{
  "InspectorName": "Jack"
}